// This is a comment syntax
var 
    hello = "hello"
    ui = 1
    ux = 88
document.getElementById("div").innerHTML = hello;
document.getElementById("div1").innerHTML = ui;
document.getElementById("div2").innerHTML = ux;
document.getElementById("div3").innerHTML = ui+ux;

// Cammel case is a way to write words :
                                        // 1 - getElementById
// getElementById used for get the element from html page -- ("div") is the element name -- .innerHTML used to know this is a html page -- "=" to set a value to element. 
// We will learn this other code in income lessons
